name: Rust

on:
  push:
    branches: [ "main", "dev-documentation"]
  pull_request:
    branches: [ "main", "dev-documentation"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
